package com.pis2015.greendaodusaexamplegen;

import java.util.List;
import com.pis2015.greendaodusaexamplegen.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHOFER".
 */
public class Chofer {

    private Long id;
    /** Not-null value. */
    private String nombre;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ChoferDao myDao;

    private List<Reparto> repartos;

    public Chofer() {
    }

    public Chofer(Long id) {
        this.id = id;
    }

    public Chofer(Long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getChoferDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Reparto> getRepartos() {
        if (repartos == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            RepartoDao targetDao = daoSession.getRepartoDao();
            List<Reparto> repartosNew = targetDao._queryChofer_Repartos(id);
            synchronized (this) {
                if(repartos == null) {
                    repartos = repartosNew;
                }
            }
        }
        return repartos;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetRepartos() {
        repartos = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
