package com.pis2015.greendaodusaexamplegen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pis2015.greendaodusaexamplegen.Reparto;
import com.pis2015.greendaodusaexamplegen.Chofer;

import com.pis2015.greendaodusaexamplegen.RepartoDao;
import com.pis2015.greendaodusaexamplegen.ChoferDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repartoDaoConfig;
    private final DaoConfig choferDaoConfig;

    private final RepartoDao repartoDao;
    private final ChoferDao choferDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repartoDaoConfig = daoConfigMap.get(RepartoDao.class).clone();
        repartoDaoConfig.initIdentityScope(type);

        choferDaoConfig = daoConfigMap.get(ChoferDao.class).clone();
        choferDaoConfig.initIdentityScope(type);

        repartoDao = new RepartoDao(repartoDaoConfig, this);
        choferDao = new ChoferDao(choferDaoConfig, this);

        registerDao(Reparto.class, repartoDao);
        registerDao(Chofer.class, choferDao);
    }
    
    public void clear() {
        repartoDaoConfig.getIdentityScope().clear();
        choferDaoConfig.getIdentityScope().clear();
    }

    public RepartoDao getRepartoDao() {
        return repartoDao;
    }

    public ChoferDao getChoferDao() {
        return choferDao;
    }

}
